server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/mango
    username: root
    password:
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
    password:
mybatis-plus:
  configuration:
    log-impl: ''
knife4j:
  basic:
    enable: true
    username: root
    password:
xxl:
  job:
    admin:
      # xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://xxljob:8080/xxl-job-admin
    # xxl-job, access token
    accessToken: default_token
    executor:
      # xxl-job executor appname
      appname: mango-backend
      # xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      # xxl-job executor server-info
      ip: mango-backend
      port: 9999
      # xxl-job executor log-path
      logpath: logs/jobhandler
      # xxl-job executor log-retention-days
      logretentiondays: 30